In [1]:
# Use the Azure Machine Learning data collector to log various metrics
from azureml.logging import get_azureml_logger
logger = get_azureml_logger()

In [2]:
# Use Azure Machine Learning history magic to control history collection
# History is off by default, options are "on", "off", or "show"
# %azureml history on

In [3]:
import sys, os, os.path, glob
os.environ['PYTHONHASHSEED'] = '0'
seed = 1343
import numpy as np
np.random.seed(seed)
import random as rn
rn.seed(seed)
import tensorflow as tf

# Force TensorFlow to use single thread.
# Multiple threads are a potential source of
# non-reproducible results.
# For further details, see: https://stackoverflow.com/questions/42022950/which-seeds-have-to-be-set-where-to-realize-100-reproducibility-of-training-res
session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)

from keras import backend as K
tf.set_random_seed(seed)
K.set_learning_phase(False)

sess = tf.Session(graph=tf.get_default_graph(), config=session_conf)
K.set_session(sess)

from keras.applications import InceptionV3
from keras.applications.inception_v3 import preprocess_input
from keras.layers import Dense, GlobalAveragePooling2D
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD
from keras.models import Model


Using TensorFlow backend.


In [4]:
IM_WIDTH, IM_HEIGHT, IM_CHANNELS = 224, 224, 3 #fixed size for InceptionV3

def setup_dnn():
    model = InceptionV3(weights="imagenet", include_top=False, input_shape=(IM_WIDTH, IM_HEIGHT, IM_CHANNELS)) #include_top=False excludes final FC layer
    return model

def setup_transfer_learninig(model, base_model):
    """Freeze all layers and compile the model"""
    for layer in base_model.layers:
        layer.trainable = False  
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

def setup_new_classifier(base_model, nb_classes):
    """Add last layer to the convnet
        Args:
            base_model: keras model excluding top
            nb_classes: # of classes
        Returns:
            new keras model with last layer
    """
    FC_SIZE = 1024
    
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(FC_SIZE, activation='relu')(x) #new FC layer, random init
    predictions = Dense(nb_classes, activation='softmax')(x) #new softmax layer
    model = Model(inputs=base_model.input, outputs=predictions)
    return model

def setup_finetune(model):
    """Freeze the bottom NB_IV3_LAYERS and retrain the remaining top layers.
        note: NB_IV3_LAYERS corresponds to the top 2 inception blocks in the inceptionv3 arch
        Args:
            model: keras model
    """
    NB_IV3_LAYERS_TO_FREEZE = 172
    
    for layer in model.layers[:NB_IV3_LAYERS_TO_FREEZE]:
        layer.trainable = False
    for layer in model.layers[NB_IV3_LAYERS_TO_FREEZE:]:
        layer.trainable = True
    model.compile(optimizer=SGD(lr=0.0001, momentum=0.9), loss='categorical_crossentropy', metrics=['accuracy'])
    
def save_dnn(model, folder, filename):
    filepath = os.path.join(folder, filename)
    sess = K.get_session()
    
    outputs = ["input_1", "dense_2/Softmax"]
    constant_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), outputs)
    tf.train.write_graph(constant_graph,folder,filename,as_text=False)
    #tf.train.write_graph(sess.graph.as_graph_def(), folder, filename, as_text=False)
    #tf.train.export_meta_graph()
    print('saved the graph definition in tensorflow format at: ', filepath)

def utils_files_count(directory):
    """Get number of files by searching directory recursively"""
    if not os.path.exists(directory):
        return 0
    cnt = 0
    for r, dirs, files in os.walk(directory):
        for dr in dirs:
            cnt += len(glob.glob(os.path.join(r, dr + "/*")))
    return cnt

def train_generator(folder, batch_size=16, save_to_dir=None):
    datagen =  ImageDataGenerator(
        preprocessing_function=preprocess_input,
        rotation_range=30,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True
    )
    #generated_folder = os.path.join(folder, '..', 'generated')
    if save_to_dir:
        if not os.path.exists(save_to_dir):
            os.makedirs(save_to_dir)
        else:
            utils_removeFilesInFolder(save_to_dir)

    generator = datagen.flow_from_directory(
        folder,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=batch_size,
        save_to_dir=save_to_dir
    )
    return generator

def validation_generator(folder, batch_size=16):
    #IM_WIDTH, IM_HEIGHT = 299, 299 #fixed size for InceptionV3
    datagen =  ImageDataGenerator(
        preprocessing_function=preprocess_input,
        rotation_range=45,
        width_shift_range=0,
        height_shift_range=0,
        shear_range=0,
        zoom_range=0,
        horizontal_flip=True
    )
    
    generator = datagen.flow_from_directory(
        folder,
        target_size=(IM_WIDTH, IM_HEIGHT),
        batch_size=batch_size
    )
    return generator

def utils_removeFilesInFolder(folder):
    files = glob.glob(os.path.join(folder,'*'))
    for f in files:
        os.remove(f)

def utils_generated_sample (data_folder, generated_folder, batches_length=1):
    generator = train_generator(data_folder, batch_size=16, save_to_dir=generated_folder)
    
    i = 0
    for batch in generator:
        i += 1
        if i > batches_length:
            break  # otherwise the generator would loop indefinitely
    

In [5]:
project_folder = %pwd
print("Project folder: ", project_folder)
output_folder = os.path.join(project_folder,'outputs')
data_folder = os.path.join(project_folder, 'data')
train_folder = os.path.join(data_folder, 'train')
validation_folder = os.path.join(data_folder, 'validation')
nb_classes = len(glob.glob(train_folder + "/*"))
batch_size=16
nb_epoch = 32
# load weights
model_filename = 'model.pb'
#if not os.path.exists(output_folder):
#    os.makedirs(output_folder)

Project folder:  D:\fran\Work\eShoConAI\workbench


In [6]:
# setup model
base_model = setup_dnn()
model      = setup_new_classifier(base_model, nb_classes)

# transfer learning
setup_transfer_learninig(model, base_model)

history_tl = model.fit_generator(
    train_generator(train_folder,batch_size),
    steps_per_epoch=500//batch_size, #utils_files_count(train_folder)//batch_size,
    epochs=32,
    validation_data=validation_generator(validation_folder, batch_size),
    validation_steps=100//batch_size, #utils_files_count(validation_folder)//batch_size,
    verbose=1,
    class_weight='auto')

Found 72 images belonging to 4 classes.
Found 15 images belonging to 4 classes.
Epoch 1/32
31/31 [==============================] - 14s 466ms/step - loss: 2.8521 - acc: 0.7299 - val_loss: 2.1636 - val_acc: 0.8667
Epoch 2/32
31/31 [==============================] - 11s 360ms/step - loss: 1.1527 - acc: 0.9072 - val_loss: 0.4155 - val_acc: 0.8222
Epoch 3/32
31/31 [==============================] - 12s 376ms/step - loss: 0.5939 - acc: 0.8889 - val_loss: 0.6177 - val_acc: 0.8444
Epoch 4/32
31/31 [==============================] - 11s 362ms/step - loss: 0.0460 - acc: 0.9858 - val_loss: 0.8475 - val_acc: 0.8556
Epoch 5/32
31/31 [==============================] - 11s 359ms/step - loss: 0.4155 - acc: 0.9255 - val_loss: 0.6814 - val_acc: 0.8444
Epoch 6/32
31/31 [==============================] - 11s 356ms/step - loss: 0.1605 - acc: 0.9718 - val_loss: 0.8954 - val_acc: 0.8444
Epoch 7/32
31/31 [==============================] - 12s 371ms/step - loss: 0.0355 - acc: 0.9899 - val_loss: 1.1398 - val_a

In [7]:
save_dnn(model, output_folder, model_filename)

INFO:tensorflow:Froze 380 variables.
Converted 380 variables to const ops.
saved the graph definition in tensorflow format at:  D:\fran\Work\eShoConAI\workbench\output\model.pb


In [8]:
#utils_generated_sample(train_folder, os.path.join(data_folder, 'generated'),2)

In [9]:
#model.get_weights()

In [10]:
print(history_tl.history.keys())

dict_keys(['val_loss', 'val_acc', 'acc', 'loss'])


In [11]:
import numpy
print ("Accuracy: ", numpy.mean(history_tl.history['acc']))

Accuracy:  0.97413962819


In [12]:
labels = ["bracelet","earrings","parasol","thermometer"]
def load_image(img_path):
    from keras.preprocessing import image
    #IM_WIDTH, IM_HEIGHT = 299, 299 #fixed size for InceptionV3
    img = image.load_img(img_path, target_size=(IM_WIDTH, IM_HEIGHT))
    x = image.img_to_array(img)
    x = numpy.expand_dims(x, axis=0)
    # https://github.com/fchollet/keras/blob/master/keras/applications/imagenet_utils.py
    # Image Transformation: channels_last & apply zero-center by mean  pixel: [103.939,116.779,123.68]
    x = preprocess_input(x)
    return x

In [13]:
bracelet_path = os.path.join(validation_folder,'bracelet','3506.jpg')
bracelet_image = load_image(bracelet_path)
preds = model.predict(bracelet_image)
print (preds)
print (labels[preds.argmax()])

[[  1.00000000e+00   3.82618243e-11   1.14727756e-08   4.17967717e-13]]
bracelet


In [14]:
earrings_path = os.path.join(validation_folder,'earrings','3451b.jpg')
earrings_image = load_image(earrings_path)
preds = model.predict(earrings_image)
print (preds)
print (labels[preds.argmax()])

[[  5.60232485e-03   9.38222706e-01   1.13637157e-04   5.60613945e-02]]
earrings


In [15]:
parasol_path = os.path.join(validation_folder,'parasol','114a.jpg')
parasol_image = load_image(parasol_path)
preds = model.predict(parasol_image)
print (preds)
print (labels[preds.argmax()])

[[  1.55161764e-20   9.88604496e-19   1.00000000e+00   1.31171620e-21]]
parasol


In [16]:
thermo_path = os.path.join(validation_folder,'thermometer','1866a.jpg')
thermo_image = load_image(thermo_path)
preds = model.predict(thermo_image)
print (preds)
print (labels[preds.argmax()])

[[  4.70502711e-19   1.33004180e-21   6.54095719e-20   1.00000000e+00]]
thermometer


In [17]:
def save_dnn2(model, folder, filename):
    filepath = os.path.join(folder, filename)
    sess = K.get_session()
    graph1 = sess.graph.as_graph_def()
    vars = {}
    for v in tf.trainable_variables():
        vars[v.value().name] = sess.run(v)
    
    with tf.Graph().as_default() as graph2:
        consts = {}
        for k in vars.keys():
            consts[k] = tf.constant(vars[k])
        tf.import_graph_def(graph1,input_map={name:consts[name] for name in consts.keys()})
        
        tf.train.write_graph(sess.graph_def,folder,filename,False)
        #tf.train.write_graph(sess.graph.as_graph_def(), folder, filename, as_text=False)
        print('saved the graph definition in tensorflow format at: ', filepath)

In [18]:
#save_dnn2(model, output_folder, 'model2.pb')

In [19]:
print (model.input.name)
print (model.output.name)

input_1:0
dense_2/Softmax:0


In [20]:
def save_dnn3(model, folder, filename):
    filepath = os.path.join(folder, filename)
    sess = K.get_session()
    graph = sess.graph.as_graph_def()
    
    outputs = ["dense_2/Softmax"]
    constant_graph = tf.graph_util.convert_variables_to_constants(sess, graph, outputs)
    tf.train.write_graph(constant_graph,folder,filename,False)

In [21]:
#save_dnn3(model, output_folder, 'model3.pb')

In [22]:
#model.get_output_at("batch_normalization_1/keras_learning_phase")

In [23]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 111, 111, 32) 96          conv2d_1[0][0]                   
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 111, 111, 32) 0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
conv2d_2 (

__________________________________________________________________________________________________
mixed8 (Concatenate)            (None, 5, 5, 1280)   0           activation_72[0][0]              
                                                                 activation_76[0][0]              
                                                                 max_pooling2d_4[0][0]            
__________________________________________________________________________________________________
conv2d_81 (Conv2D)              (None, 5, 5, 448)    573440      mixed8[0][0]                     
__________________________________________________________________________________________________
batch_normalization_81 (BatchNo (None, 5, 5, 448)    1344        conv2d_81[0][0]                  
__________________________________________________________________________________________________
activation_81 (Activation)      (None, 5, 5, 448)    0           batch_normalization_81[0][0]     
__________

In [24]:
#save_dnn(model, output_folder, model_filename)

In [25]:
thermo_image.shape

(1, 224, 224, 3)